spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/project?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
openweathermap:
  key: 58f2e352203c44498cfa591ae748a593
logging:
  config: classpath:logback-spring.xml